services:
  stockmarketsimulator-api:
    image: ${DOCKER_REGISTRY-}stockmarketsimulatorapi
    build:
      context: .
      dockerfile: StockMarketSimulator.Api/Dockerfile
    ports:
     - 5000:8080
     - 5001:8081

  stockmarketsimulator-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=stock-market-simulator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  stockmarketsimulator-seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
