services:
  # stockmarketsimulator-api:
  #   image: ${DOCKER_REGISTRY-}stockmarketsimulatorapi
  #   container_name: stockmarketsimulator-api
  #   build:
  #     context: .
  #     dockerfile: StockMarketSimulator.Api/Dockerfile
  #   ports:
  #    - 5000:8080
  #    - 5001:8081

  stockmarketsimulator-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=stock-market-simulator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  stockmarketsimulator-seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

  stockmarketsimulator-cache:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
     - 6379:6379  

  stockmarketsimulator-papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut
    ports:
      - 8080:80
      - 25:25

  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
     - 5000:8080
     - 5001:8081

